using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Text;
using System.Windows.Forms;
using DXP;
using EDP;
using SCH;
using PCB;

public class Commands 
{
    //Autogenerated code. Commands implementation. Begin
    public void CommandReleasePartChoices(IServerDocument view, string parameters)
    {
        ReleasePartChoices();
    }
    //Autogenerated code. Commands implementation. End

    private void ReleasePartChoices()
    {
        var vaultManager = EDP.Utils.GetVaultManager();

    }
}

