using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Text;
using System.Windows.Forms;
using DXP;
using EDP;

namespace CSharpPlugin
{
    public interface IPluginFactory
    {
        object InvokePluginFactory(IClient a);
    }

    [ClassInterface(ClassInterfaceType.None)]
    public class PluginFactory : IPluginFactory
    {
        public object InvokePluginFactory(IClient a)
        {
            PluginServerModule serverModule = new PluginServerModule(a, "SupplyChainRelease");
            return serverModule;
        }
    }

    [ClassInterface(ClassInterfaceType.AutoDispatch)]
    public class PluginServerModule : ServerModule
    {
        public PluginServerModule(IClient argClient, string argModuleName)
            : base(argClient, argModuleName)
        {
        }

        protected override void InitializeCommands()
        {
            //Autogenerated code. Commands registration. Begin
            //Autogenerated code. Commands registration. End
        }

        protected override IServerDocument NewDocumentInstance(string kind, string fileName)
        {
            return null;
        }

       //Autogenerated code. Commands definition. Begin
       //Autogenerated code. Commands definition. End
    }
}
