using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Text;
using System.Windows.Forms;
using DXP;
using EDP;

namespace CSharpPlugin
{
    public interface IPluginFactory
    {
        object InvokePluginFactory(IClient a);
    }

    [ClassInterface(ClassInterfaceType.None)]
    public class PluginFactory : IPluginFactory
    {
        public object InvokePluginFactory(IClient a)
        {
            PluginServerModule serverModule = new PluginServerModule(a, "ContentTeamTools");
            return serverModule;
        }
    }

    [ClassInterface(ClassInterfaceType.AutoDispatch)]
    public class PluginServerModule : ServerModule
    {
        public PluginServerModule(IClient argClient, string argModuleName)
            : base(argClient, argModuleName)
        {
        }

        protected override void InitializeCommands()
        {
            //Autogenerated code. Commands registration. Begin
		((CommandLauncher)CommandLauncher).RegisterCommand("CleanupSamtecSymbols", this.Command_CleanupSamtecSymbols);
        ((CommandLauncher)CommandLauncher).RegisterCommand("AddCourtyard", this.Command_AddCourtyard);
        ((CommandLauncher)CommandLauncher).RegisterCommand("AddCenterMark", this.Command_AddCenterMark);
        ((CommandLauncher)CommandLauncher).RegisterCommand("CleanupSamtecFootprints", this.Command_CleanupSamtecFootprints);
        ((CommandLauncher)CommandLauncher).RegisterCommand("CountFootprintPrimitives", this.Command_CountFootprintPrimitives);
        ((CommandLauncher)CommandLauncher).RegisterCommand("CountPinsOfSymbol", this.Command_CountPinsOfSymbol);
        ((CommandLauncher)CommandLauncher).RegisterCommand("RemoveSymbolVaultLink", this.Command_RemoveSymbolVaultLink);
            //Autogenerated code. Commands registration. End
        }

        protected override IServerDocument NewDocumentInstance(string kind, string fileName)
        {
            return null;
        }

       //Autogenerated code. Commands definition. Begin

		//Autogenerated code. Begin of definition [Command_CleanupSamtecSymbols]
		private void Command_CleanupSamtecSymbols(IServerDocumentView argView, ref string argParameters)
        {
            new Commands().Command_CleanupSamtecSymbols(argView, ref argParameters);
            return;
        }

        private void Command_AddCourtyard(IServerDocumentView argView, ref string argParameters)
        {
            new Commands().Command_AddCourtyard(argView, ref argParameters);
            return;
        }

        private void Command_AddCenterMark(IServerDocumentView argView, ref string argParameters)
        {
            new Commands().Command_AddCenterMark(argView, ref argParameters);
            return;
        }

        private void Command_CleanupSamtecFootprints(IServerDocumentView argView, ref string argParameters)
        {
            new Commands().Command_CleanupSamtecFootprints(argView, ref argParameters);
            return;
        }

        private void Command_RemoveSymbolVaultLink(IServerDocumentView argView, ref string argParameters)
        {
            new Commands().Command_RemoveSymbolVaultLink(argView, ref argParameters);
            return;
        }

        private void Command_CountFootprintPrimitives(IServerDocumentView argView, ref string argParameters)
        {
            new Commands().Command_CountFootprintPrimitives(argView, ref argParameters);
            return;
        }

        private void Command_CountPinsOfSymbol(IServerDocumentView argView, ref string argParameters)
        {
            new Commands().Command_CountPinsOfSymbol(argView, ref argParameters);
            return;
        }
		//Autogenerated code. End of definition [Command_CleanupSamtecSymbols]

       //Autogenerated code. Commands definition. End
    }
}
